title: School of Erlang - December 2016
description: During this edition of the School of Erlang students are building chatbots running on RaspberryPi and communicating with humans through XMPP messengers.
theme: jekyll-theme-minimal
